# Generated by Django 4.1 on 2022-08-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="featured_image",
            field=models.ImageField(default=1, upload_to="post_images/%Y/%m/%d"),
            preserve_default=False,
        ),
    ]
