# Generated by Django 4.1 on 2022-09-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_blog', '0002_post_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='post',
            name='featured_post',
            field=models.BooleanField(default=False),
        ),
    ]
